---
- include_tasks: deps.yml
  when: installed_acme_deps is not defined

- include_tasks: acme.yml

- include_role:
    name: bviktor.setfcontext
  vars:
    path: '/root/.acme.sh'
    type: 'cert_t'
    pattern: "/root/.acme.sh(/.*)?"
  when: ansible_os_family == 'RedHat'

- include_tasks: cron.yml
  when: eff_cronjob
