---
- include_tasks: main2.yml
  vars:
    domain: "{{ item.domain }}"
    provider: "{{ item.provider }}"
    credential: "{{ item.credential }}"
    wildcard: "{{ item.wildcard | default('') }}"
    cronjob: "{{ item.cronjob | default('') }}"
    staging: "{{ item.staging | default('') }}"
    sleep: "{{ item.sleep | default('') }}"
    min_days: "{{ item.min_days | default('') }}"
    reload_cmd: "{{ item.reload_cmd | default('') }}"
  loop: "{{ acme_batch }}"
  loop_control:
    # make sure we don't leak credentials to stdout lol
    label: "{{ item.domain }}"
  when: (acme_batch is defined) and (acme_batch.__class__.__name__ == 'list')

- include_tasks: main2.yml
  when: (acme_batch is not defined) or (acme_batch.__class__.__name__ != 'list')
